pulumi/pulumi-docker

docker/docker.ts
docker/image.ts
docker/index.ts
docker/package.json
docker/tests/image/Pulumi.yaml
docker/tests/image/index.ts
docker/tests/image/mynginx/Dockerfile
docker/tests/image/mynginx/html/index.html
docker/tests/image/package.json
docker/tests/image/tsconfig.json
docker/tests/image/yarn.lock

The docker.Image component adds a nice interface over building and pusshing an image to a Docker registry, and getting a handle to the resulting image name and digest.
This can be used with any Docker registry.  For example, to push to Docker Hub:
```javascript
const image = new docker.Image("mynginx", {
imageName: "hekul/mynginx:v1",
build: "./mynginx",
registry: {
name: "docker.io",
username: dockerUsername,
password: dockerPassword,
},
});
export const dockerImageName = image.imageName;
```
Also fixes a bug in how `digest` was being computed previously - this was reading the `Id` property off of `docker image inspect`, which is turns out is not the digest we were looking for (and critically, not the digest that can be used to pin an image version).
Fixes #2.

Add docker.Image component

---

docker/docker.ts
docker/image.ts
docker/index.ts

In #10, we "fixed" buildAndPushAsync to return the image repo digest instead of the image id.  The former is more useful as it can be applied as a digest version to pin a specific built image and force updates when that image changes.
However, the repo digest is not available for images that have not yet been pushed/pulled from a repository.  Moreover, the repo digest must be looked up by the repo-tagged name (and apparently the digest can differ across repos even for the same image), not by a local-only tag.
The combination of these two factors broke the way we use `pulumi-docker` from `pulumi-cloud`, and introduced the bug in pulumi/pulumi-cloud#595 where the `IMAGE_DIGEST` env var was always getting set to an empty string.  (notably, that env var is misnamed, it was previously the …

Revert buildAndPushImageAsync to return Id instead of Digest

---

docker/docker.ts
docker/image.ts

this is especially useful when using docker credential helpers which already handle auth to the target registry.
fixes #16

make docker registry credentials optional

---

docker/docker.ts
docker/package.json
docker/yarn.lock

Fixes: https://github.com/pulumi/pulumi/issues/2052
Normal docker spew is simply captured as ephemeral messages (so you can see what's going on), without reprinting it.  If, however, any errors do occur, then we will print out the messages.
Docker output now looks like:
During execution you see stuff like:

Only print out docker messages in the event of warnings/failures.

---

docker/docker.ts
docker/image.ts
docker/yarn.lock

We now tag all our docker pushed builds with a tag equal to their image-id.  i.e. we'll end up tagging a build like so:
`<awsid>.dkr.ecr.<region>.amazonaws.com/image-name:<image-id>` or
`<awsid>.dkr.ecr.<region>.amazonaws.com/image-name:<user-tag>-<image-id>`
By adding teh image-id into the tag name, we then have a unique and stable name for the target build that can be known at preview time.  It also means that any time docker produces a new image id, we end up replacing the image.  This helps us avoid needing to hack things in at the cloud layer where we place hte image-id in the environment variable map in order to get pulumi to want to replace the cloud.Service resource.
As part of this change docker.buildAndPushImage now retursn that entire target name, instead of just returning the …

Tag docker target images with a unique name

---

docker/docker.ts

Fixes issue where we were incorrectly skipping logging into a docker registry when doing a parallel update with many resources coming from the same registry.  The problem stemmed from a previous PR where we tried to prevent logging into the same docker registry multiple times.  That change was buggy in that it recorded we were logged in prior to actually executing the login.  That meant that when one update was actually doing the login (asynchronously), another resource could then move forward, try to login, think it was logged in (even though the first hadn't completed) and then would continue on to further docker operations which would then fail. 
This change now makes it so that we store around the actual promise tracking the real login.  While that login is asynchonously computing, if …

Ensure we do always login to a registry when issuing multiple login requests to the same one.

---

CHANGELOG.md
sdk/nodejs/docker.ts

Add the ability to specify extra `docker build` CLI options that can be provided to `buildAndPushImage()`.
Allows you to specify things like `--network host` or others, without having to semantically enumerate every option of the docker `CLI` in this interface.

Add ability to specify extra options for docker build.

---

sdk/nodejs/docker.ts

This is an experiment to see if we can workaround the async-invoke problem downstream by ensuring that we make all docker calls *after* our call to get the registry info.

Frontload logging into the registry before we do any actual docker calls

---

CHANGELOG.md
sdk/nodejs/docker.ts

Fixes: https://github.com/pulumi/pulumi-docker/issues/56
Not specifying a tag when building an image makes it use `latest`, this causes Pulumi to overwrite the first image build when deploying multiple images that use the same repository but different tags.

prevent tags from being stripped for the build image names

---

CHANGELOG.md
examples/dockerfile-with-targets/.gitignore
examples/dockerfile-with-targets/Dockerfile
examples/dockerfile-with-targets/Pulumi.yaml
examples/dockerfile-with-targets/index.ts
examples/dockerfile-with-targets/package.json
examples/dockerfile-with-targets/tsconfig.json
examples/examples_test.go
sdk/nodejs/docker.ts

Fixes: #37
This allows a user to use a multi-target Dockerfile

Allow a user to pass a build target to image.Image in nodejs SDK

---

sdk/nodejs/docker.ts
sdk/nodejs/image.ts

Break was added in https://github.com/pulumi/pulumi-docker/pull/114, but has not been released to customers yet.  This def breaks awsx.

Fix binary/source breaking change when parameter was added.

---

CHANGELOG.md
resources.go
sdk/dotnet/ServiceConfig.cs
sdk/go/docker/serviceConfig.go
sdk/nodejs/index.ts
sdk/nodejs/serviceConfig.ts
sdk/nodejs/tsconfig.json
sdk/python/pulumi_docker/__init__.py
sdk/python/pulumi_docker/service_config.py

Fixes: #140
We had `docker_config` being created as `Config` in the NodeJS, Go
and Python packages. This was actually colliding with the `Config`
module of each of the packages but was particularly breaking the
Python integration. We are going to accept that this is technically
a breaking change BUT that it's for the better since it actually
makes the Config module usable
The DotNet SDK was already using `ServiceConfig` so we made the
other SDKs similar to this

Changing the Name of the docker Config resource to be ServiceConfig

---

examples/nginx-go/Gopkg.toml
examples/nginx-go/Pulumi.yaml
examples/nginx-go/main.go

This is the first step towards #128 and basically just the Go implementation of the existing `nginx` tests.

Add remote image test for Go

---

go.mod
sdk/go/docker/docker.go

Relies on pulumi/pulumi#4069.
Most of the changes here boil down to:
- Including `pulumi.Context` in the function headers
- Changing all instances of `logging.Infof` to `logEphemeral` which is just `ctx.Log.Info(...)`

Update logging to use Pulumi engine

---

.travis.yml

Related to pulumi/home#845.
The `master` branch build failed during the integration test phase due to the AWS creds that were changed with https://github.com/pulumi/pulumi-docker/pull/171 having insufficient access to create AWS resources. This PR updates the Travis config file to use the right AWS profile. But that's only one part of it. The other part is that I will update the AWS creds in the Travis settings for this repo to use the creds that would allow it to use that profile.

Use pulumi-ci AWS profile.

---

sdk/go/docker/image.go

Fixes: #183
The logic wasn't correct here - we were appending the tag when there
was no tag

Ensure the docker ImageName is formed correctly in Go SDK

---

.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
CHANGELOG.md
examples/dockerfile-go/main.go
examples/dockerfile-py/__main__.py
examples/dockerfile-with-targets/index.ts
examples/dotnet/Program.cs
examples/examples_go_test.go
sdk/go/docker/customTypes.go
sdk/nodejs/docker.ts
sdk/python/pulumi_docker/docker.py

This change makes sure that any environment variables passed in are appended to the current OS env vars. Adds tests to document behavior across languages.
Fixes https://github.com/pulumi/pulumi-docker/issues/196
Note: there is a breaking change for go types for Args and Env, but this is in the category of "never worked in the first place". The unmarshalling fails when you specify environment variables as is, so this change to types just makes it work as intended.

consistently handle environment variables

---

CHANGELOG.md
sdk/python/pulumi_docker/docker.py

Note: There are still some uses of `List[T]` that remain for lists used internally that are mutated (hence why the `List` import remains).

Python: Use Sequence instead of List in overlays

---

CHANGELOG.md
sdk/dotnet/Docker.cs

Fix #200
There is a race condition in the .NET SDK. As observed in a local test, `Exited` event may fire before the last `OutputDataReceived` call. If that happens, the last chunk of the output won't [be appended](https://github.com/pulumi/pulumi-docker/blob/395a9ac83377aa3ec290100dfd7c812db749100a/sdk/dotnet/Docker.cs#L608) to `stdout`. The `inspect` command returns a single chunk of output. If it's missing, the output is empty, and the exception `"No digest available for image"` is fired.
One possible fix would be to wait for a call with [`e.Data`](https://github.com/pulumi/pulumi-docker/blob/395a9ac83377aa3ec290100dfd7c812db749100a/sdk/dotnet/Docker.cs#L605) equal to `null` which signals the completion of the output. 
A simpler solution is suggested …

Fix a race condition of not getting all the output in .NET Image

---

CHANGELOG.md
examples/examples_dotnet_test.go
examples/examples_go_test.go
examples/examples_nodejs_test.go
examples/examples_py_test.go
examples/go.sum
examples/util.go
sdk/dotnet/Docker.cs
sdk/go/docker/docker.go
sdk/nodejs/docker.ts
sdk/python/pulumi_docker/docker.py

Makes a variety of improvements to the log output of the build and push steps, both for cross-language consistency, and for a more focused and useful default display.
Improvements include:
* Significantly reduce the diagnostic-level output  - render just start/end notes for build and push steps - plus streamed output from docker build and docker push.
* Keep diagnostic logs as "debug" level logs
* Correctly stream stdout to ephemeral logs for Go
* Fix incorrect newline handling of streamed stdout in Node.js
* Add tests of CLI output

Improve build and push output

---

sdk/go/docker/customTypes.go
sdk/go/docker/docker.go
sdk/go/docker/image.go

Looks like we are using `golangci/golangci-lint:latest` for running linting and perhaps the format for specifying nolints has recently changed. Also fixes a bug related to `cache_from` handling. This is independent of https://github.com/pulumi/pulumi-docker/issues/238

Fix various go linting issues

---

CHANGELOG.md
sdk/python/pulumi_docker/docker.py

This swaps out subprocess.Popen and communicate calls, which
block, when invoking the Docker CLI, and instead uses
asyncio.create_subprocess_exec, which offers equivalent functionlity
without blocking the message loop.
This addresses the responsiveness issues and behaves better with
the Pulumi CLI. In particular, for lengthy builds, we no longer
interfere with the ability of the CLI to report progress and display
resources as they are created by the program, asynchronously
interleaved amongst the build itself.
This is technically a breaking change, however, because the
functions now return futures where they used to return raw values.
It would be reasonable to, instead of changing these in place,
turn them into _async routines (which are used internally), and
then have thin wrappers that …

Don't block the message loop on Docker builds

---

provider/cmd/pulumi-resource-docker/schema.json
provider/resources.go
sdk/dotnet/Pulumi.Docker.csproj

Fixes: #357
We want to inherit the upstream dep from Pulumi not override it otherwise we get a downgrade warning with Nuget

[internal] Ensure DotNet dependencies match those upstream

---

CHANGELOG.md
sdk/python/pulumi_docker/docker.py

Fixes #310 
The `update()` method modifies a dictionary and returns `None`, not the modified dictionary. The original code passed this return value from `update()` to `subprocess.Popen()` as the environment variables rather than the dictionary which was updated. This PR fixes this by passing the modified dictionary.

Fix passing of env variables to docker build

---

sdk/python/pulumi_docker/docker.py

I got this issue
```
/.../lib/python3.9/site-packages/pulumi_docker/docker.py:232: RuntimeWarning: coroutine 'use_docker_password_stdin' was never awaited
await login_to_registry(registry, log_resource)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
I added `await` and it worked. I didn't make full blown investigation, but I don't want others to get this error.

Missing `await` statement in `use_docker_password_stdin`

---

.github/workflows/prerelease.yml

On an alpha release, we run the prerelease action. pulumictl needs to read a version prefix, otherwise the Go SDK will fail to build.

Add VERSION_PREFIX to prerelease Action

---

.github/workflows/prerelease.yml

Add env var for pulumictl to recognize a prerelease tag
Similar to https://github.com/pulumi/pulumi-awsx/blob/master/.github/workflows/pre-release.yml#L20.

Add IS_PRERELEASE:true to prerelease action workflow

---

provider/image.go
provider/image_test.go

This PR cleans up the input verification for Image and adds unit tests.
There are a few minor code changes mostly as a result of adding test cases.
Fixes #420
- refactor test case declaration
- Add tests for setRegistry. Harden setRegistry against nil interface values.
- Add first pass of marshalBuild tests
- Separate getting args and env into helper functions. Add basic test coverage for both
- Refactor Registry tests into suite
- clean up test case declaration for registry
- Add TestGetCachedImages
- Do not set empty maps for Args and Env
- Test ExtraOptions

Add Unit Tests for Input Parsing

---

provider/hybrid.go
provider/provider.go

See: https://github.com/pulumi/pulumi/issues/11616
This change ensures the Docker provider is source-code forward compatible with future changes to the gRPC interfaces for providers upstream. This reduces the likelihood that source code changes are needed when updating to new Pulumi SDK/PKG versions.
The same change is being made in the bridge and other providers to ensure that CI systems can reliably build and test new versions of the core Pulumi engine against providers.

Ensure forward build compatibility for resource provider

---

provider/cmd/pulumi-resource-docker/schema.json
provider/image.go
provider/resources.go
sdk/dotnet/Inputs/RegistryArgs.cs
sdk/go/docker/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/docker/inputs/RegistryArgs.java
sdk/nodejs/types/input.ts
sdk/python/pulumi_docker/_inputs.py

Fixes #442.
This PR includes a slight tweak to the schema, requiring only the `server` field of the `registry` type to be required when using `registry`.
SDKs were regenerated accordingly.
Adds new logic to use Docker config file credentials when username and passworkd are not provided via the Pulumi program.
- Do not make registry Username and Password required
- Enable use of  Docker configuration for push registry authentication

Use Docker credentials file to log in to registry

---

provider/provider.go

When the `build` field is unset entirely, the Check function was
panicking attempting to set the implicit `contextDigest` field.
This PR properly constructs the `inputs["build"]` field as a
`resource.NewObjectProperty`.

Fix panic in Check function

---

provider/image.go

Warnings should persist after running pulumi up.
Fixes #463.

Set Warning to write to persistent logs

---

provider/cmd/pulumi-resource-docker/schema.json
provider/image.go
provider/image_test.go
provider/resources.go
sdk/dotnet/Inputs/CacheFromArgs.cs
sdk/dotnet/Inputs/DockerBuildArgs.cs
sdk/go/docker/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/docker/inputs/CacheFromArgs.java
sdk/java/src/main/java/com/pulumi/docker/inputs/DockerBuildArgs.java
sdk/nodejs/types/input.ts
sdk/python/pulumi_docker/_inputs.py

Fixes #427
Fixes #426
The v3.x.x implementation of cacheFrom did not properly reflect its use as a Docker command flag.
This pull request enables the `cacheFrom` type on the `build` type of `docker.Image` resource.
It accepts a list of images that can be pulled from an authenticated registry to serve as a build cache.
These images must have caching metadata information associated; otherwise Docker won't find them and build without cache.
This PR in its current state removes the OneOf implementation for `cacheFrom`, requiring the developer to explicitly add any image names to the `images` list. I am happy to revert this removal if we consider it necessary.
There is also a slight tweak to log handling output to avoid printing bytes 😅 
- re-schematize cacheFrom to properly reflect its use in …

Add Cache From feature

---

examples/dockerfile-go/main.go
examples/dockerfile-py/__main__.py
examples/dockerfile-with-targets/index.ts
examples/dotnet/Program.cs
provider/cmd/pulumi-resource-docker/schema.json
provider/image.go
provider/image_test.go
provider/resources.go
sdk/dotnet/Inputs/DockerBuildArgs.cs
sdk/go/docker/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/docker/inputs/DockerBuildArgs.java
sdk/nodejs/types/input.ts
sdk/python/pulumi_docker/_inputs.py

This PR cleans up:
`env` - it was used to pass CLI environment variables like `BUILDKIT=1` and we now have `builderVersion` instead
`extraOptions` - we cannot support a grab bag of command line options when using the docker SDK.
- Remove `env` from schema
- Remove handling of deprecated `env` field from Image implementation
- Generate SDKs for removal of `env` type
- Remove `extraOptions` field
- Remove extraOptions implementation and tests
- Regenerate SDKs
Fixes #469

Deprecate extraOptions and env

---

provider/cmd/pulumi-resource-docker/schema.json
provider/image.go
provider/image_test.go
provider/resources.go
sdk/dotnet/Inputs/DockerBuildArgs.cs
sdk/go/docker/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/docker/inputs/DockerBuildArgs.java
sdk/nodejs/types/input.ts
sdk/python/pulumi_docker/_inputs.py

This schematizes the `platform` build field, which provides
cross-platform build abilities akin to the docker CLI's `--platform`
flag.
When set, the provider will build an image for the platform specified.
Fixes #470
Fixes #296
- Add Platform build input
- Generate SDKs

Enable cross platform builds

---

.github/workflows/master.yml

[experimental] GoReleaser was not downloaded on a recent publish step on default branch.
We're two versions behind on the goreleaser action so this is an attempt to fix via version bump.

Bump goreleaser action

---

provider/go.mod
provider/go.sum
provider/image.go

On various platforms, the Docker credentials store may return keys with URLs with a scheme ("https://") prefixed on all entries, or hostnames only. An exception to this is the legacy Docker index server, which appears as "https://index.docker.io/v1/".
The push auth config is now selected by first resolving a valid ("non-legacy") entry, which will be either a hostname aka registry name, or the "https://index.docker.io/v1/" value. This value is then passed to `GetAuthConfig`, using the Docker library's existing lookup fallback behavior to handle URLs.
Two additional legacy names are handled, as discovered by reading the ORAS' project's implementation with the same goal. See:
https://github.com/oras-project/oras-go/blob/v1.2.2/pkg/auth/docker/resolver.go#L79-L86

fix: Docker auth config lookup portability

---

provider/cmd/pulumi-resource-docker/schema.json
provider/resources.go
sdk/dotnet/Image.cs
sdk/go/docker/image.go
sdk/java/src/main/java/com/pulumi/docker/Image.java
sdk/nodejs/image.ts
sdk/python/pulumi_docker/image.py

Adds the alias for the v3.x.x Docker image URN token to the new, schematized Image token.
Specifically, `docker:index/image:Image` is aliased to the previous `docker:index:Image`.
This should avoid delete/create of a resource during upgrade to v4.
- Add alias to Image
- generate schema and SDKs

Alias Docker image to avoid deletion on upgrade to v4

---

provider/image.go

Implements passing the `target` input field to the ImageBuildOptions.
This is likely going to see little use, as registry caching is so much faster using Buildkit mode, so support should be minimal.
Fixes #425.

Implement Target

---

provider/image.go

This pull request adds an extra error handling step to the logging output.
In the case of a `docker push` to AWS, when credentials are incorrect or mismatched, we sometimes see Docker re-trying a push multiple times, only to ultimately fail with an uninformative `error: EOF`. This extra condition intercepts this error and adds more detail to the output.
Fixes #485

Add EOF condition to special error case handling

---

provider/provider.go

It turns out even Windows builds for Linux by default when using Docker.
This PR leaves the logic for architecture, but defaults to use Linux as the platform OS.
Fixes #534

Always assume Linux for host OS

---

Makefile

Removes circular dependency in Makefile, which prevented the schema-embed.json from being written correctly to cmd/pulumi-resource-docker in the publish step in CI.
We do not actually need for the docs build to depend on the provider build, sinc the docs are a prerequisite to generating the schema.
Fixes #545.

Docs target should not depend on provider target

---

examples/aws-container-registry/py/requirements.txt
examples/aws-container-registry/ts/index.ts
examples/digitalocean-container-registry/py/requirements.txt
examples/docker-container-registry/csharp/Program.cs
examples/docker-container-registry/go/main.go
examples/docker-container-registry/py/__main__.py
examples/docker-container-registry/py/requirements.txt
examples/docker-container-registry/ts/index.ts
examples/examples_go_test.go
examples/examples_nodejs_test.go
examples/gcp-container-registry/py/requirements.txt
provider/cmd/pulumi-resource-docker/schema.json
provider/image.go
provider/resources.go
sdk/dotnet/Image.cs
sdk/go/docker/image.go
sdk/java/src/main/java/com/pulumi/docker/Image.java
sdk/nodejs/image.ts
sdk/python/pulumi_docker/image.py

The Image.repoDigest property was removed in v4 as part of the transition to use the Docker SDK instead of the Docker CLI. Fortunately the SDK exposes a method that makes it easy to construct the repo digest.
Fix #507.

Restore Image.repoDigest output

---

provider/image.go
provider/image_test.go
provider/provider.go

fixes https://github.com/pulumi/pulumi-docker/issues/532
This fix avoids a panic in pkg/pulumi by verifying that the `images` property is non-null when using `cacheFrom`. It also adds verification in the `Preview` step, which avoids the user experience of discovering the error on `Update`

check for images property if cacheFrom is present

---

provider/image.go
provider/image_test.go

Because Image is part of the native provider, we need to be able to pass configurations to it as well. This change allows users to set the hostname for the docker host in their configuration file.
Fixes #567.
Closes #51 as well.

Read docker host from config

---

examples/examples_nodejs_test.go
examples/examples_yaml_test.go
examples/test-unknowns/ts/Dockerfile
examples/test-unknowns/ts/Pulumi.yaml
examples/test-unknowns/ts/index.ts
examples/test-unknowns/ts/package.json
examples/test-unknowns/ts/tsconfig.json
examples/test-unknowns/yaml/Dockerfile
examples/test-unknowns/yaml/Pulumi.yaml
provider/provider.go

When we try to access a Build object which contains unknown values in the Check() function, the provider panics, because the Build object is not of the correct resource type.
This pull request ignores unknowns when reading inputs in Check(), allowing for the resulting object to be processed correctly.
Fixes #565.

Skip unknowns in Check to avoid panic when marshalling Build object

---

provider/image.go
provider/image_test.go
provider/provider.go

In #555 we addressed a panic for an empty `cacheFrom` object.
We added a verificaton step at the Check() function to fail early.
This introduced a panic created by passing unknowns to marshalCachedImages.
This pull request refines the logic in the marshalling function to handle unknowns, catches possible panics via returning a helpful error, and adds tests for these additional scenarios.
Fixes #576.
- Improve error messaging for input verification when called during Check() Move verification to its own if block
- Add tests to verify cacheFrom marshaling

fix: return reasonable errors for cache marshaling and allow for unknowns to pass through

---

examples/dockerfile_test.go
examples/test-dockerfile/dockerignore-default-fail/.dockerignore
examples/test-dockerfile/dockerignore-default-fail/Dockerfile
examples/test-dockerfile/dockerignore-default-fail/Pulumi.yaml
examples/test-dockerfile/dockerignore-default-fail/app.txt
examples/test-dockerfile/dockerignore-default-fail/ignore.txt
examples/test-dockerfile/dockerignore-default/.dockerignore
examples/test-dockerfile/dockerignore-default/Dockerfile
examples/test-dockerfile/dockerignore-default/Pulumi.yaml
examples/test-dockerfile/dockerignore-default/app.txt
examples/test-dockerfile/dockerignore-default/ignore.txt
examples/test-dockerfile/dockerignore-no-mapping/.dockerignore
examples/test-dockerfile/dockerignore-no-mapping/Mockerfile
examples/test-dockerfile/dockerignore-no-mapping/Pulumi.yaml
examples/test-dockerfile/dockerignore-no-mapping/app.txt
examples/test-dockerfile/dockerignore-no-mapping/ignore.txt
examples/test-dockerfile/dockerignore-specified/Mockerfile
examples/test-dockerfile/dockerignore-specified/Mockerfile.dockerignore
examples/test-dockerfile/dockerignore-specified/Pulumi.yaml
examples/test-dockerfile/dockerignore-specified/app.txt
examples/test-dockerfile/dockerignore-specified/ignore.txt
examples/test-dockerfile/dockerignore-with-external-dockerfile/Dockerfile
examples/test-dockerfile/dockerignore-with-external-dockerfile/Pulumi.yaml
examples/test-dockerfile/dockerignore-with-external-dockerfile/app/.dockerignore
examples/test-dockerfile/dockerignore-with-external-dockerfile/app/app.txt
provider/image.go
provider/image_test.go
provider/provider.go

Docker can map .dockerignore files to dockerfiles 
via the following behavior:
1. `Dockerfile` maps to `.dockerignore`
2. `CustomNameDockerfile` maps to `CustomNameDockerfile.dockerignore`.
This PR adds that mapping, uses it in appropriate locations, and verifies behavior with unit and integration tests.
Fixes #568 
- Add function to map additional dockerignore files.
- Add integration tests for .dockerignore

Support additional .dockerignore formats

---

provider/provider.go
provider/provider_test.go
provider/testdata/unignores/basedir-with-unignored-files/.dockerignore
provider/testdata/unignores/basedir-with-unignored-files/Dockerfile
provider/testdata/unignores/basedir-with-unignored-files/top-dir/subdir/app.js
provider/testdata/unignores/basedir/Dockerfile
provider/testdata/unignores/basedir/top-dir/subdir/app.js

This pull request fixes an assumption that we had hoped to leverage for speeding up our context hash function.
When we walk the build context directory, we skipped walking directories that were declared as dockerignored, assuming that we need not check the individual contents of an ignored directory.
However, it is possible to un-ignore files and directories.
Hence, in the case of _unignoring_ a previously ignored directory, this skip will result in now un-ignored files not being written to the context hash.
A possible side effect of this change is slower performance on Check, as we now need to be walking all individual files. 
Fixes #594.

Do not skip ignored folders in hash function

---

provider/image.go
provider/provider.go
provider/provider_test.go
provider/testdata/dockerfile-location-irrelevant/app/foo.sh
provider/testdata/dockerfile-location-irrelevant/step1.Dockerfile
provider/testdata/dockerfile-location-irrelevant/step2.Dockerfile

This fixes #578 by refactoring context hashing to not rely on a relative Dockerfile path. This check was a little error-prone, because it didn't account for forward slashes on Windows as a valid path separator.
```go
if strings.Contains(dockerfile, string(filepath.Separator)) {
```
However, we don't need to compute the relative path for the Dockerfile if we change `hashContext` to allow the Dockerfile to be specified with an absolute or relative path to the project directory.
The most obvious test to include here is that if the Dockerfile is outside of the build context, the context hash is now agnostic to the name of the Dockerfile. This matches Docker's behavior, and a unit test was added accordingly.

Refactor context hash to avoid computing relative Dockerfile path

---

patches/0003-smarter-host-resolution.patch

This PR changes the `patches/0003-smarter-host-resolution.patch` to respect the host of the ssh `ConnectionHelper` as it is used in the upstream provider and in this repository before 0b2969fafcdb5e8a23460087b04917866f6f09bb.
This fixes the bug https://github.com/pulumi/pulumi-docker/issues/635 that leads to errors when using an SSH host with a username like:
```typescript
const provider = new docker.Provider("provider", {
host: "ssh://limond@localhost:22",
});
const exampleNginx = new docker.Container("example-nginx", {
image: "nginx:latest",
ports: [{
internal: 80,
external: 80,
}],
}, { provider });
```
I was unsure if changing the patch file or generating a new patch would be the right approach.

Fix not using the ConnectionHelper Host for SSH connections

---

examples/examples_dotnet_test.go
examples/examples_yaml_test.go
examples/test-secrets-in-explicit-provider/csharp/Program.cs
examples/test-secrets-in-explicit-provider/csharp/Pulumi.yaml
examples/test-secrets-in-explicit-provider/csharp/docker-640.csproj
provider/hybrid.go
provider/provider.go

Fixes https://github.com/pulumi/pulumi-docker/issues/640
Our current design for handling program-originating secrets in bridged providers is to basically let the engine (Pulumi CLI) handle it for us. Bridged providers return "acceptsSecrets=false" to the engine, which then does not pass secret bits to Configure or Create but instead passes plain data and does some heuristic matching on the resource/provider outputs to make sure secret data stays secret.
Unfortunately due to how Configure was written in dockerHybridProvider struct here which multiplexes traffic between bridged and native providers, this information got lost and the docker provider returned acceptsSecrets=true to the engine, while not protecting the bridged provider from unexpected secrets. This caused a panic deep in the …

Fix accept secrets=false to configure provider with nested secrets

---

provider/image.go

It turns out that `filepath.Abs` returns the filepath with the os separator for the os we're running on.
We then call `filepath.Rel` on the Dockerfile and the docker context. 
If a Dockerfile is more than one folder away from its context, it means its relative path now contains the filepath separators for the host os. 
When that gets re-added to the build tarball by Docker, the client cannot open the Dockerfile on Windows because it contains backslashes in the final bit of its filepath:
`/var/lib/docker/tmp/buildkit-mount1961648446/EchoApp\Dockerfile`
With this PR, we ensure the relative path for the Dockerfile contains only forward (unix-style) slashes.
We verified that this runs correctly on Windows now.
Fixes #624.

Fix Windows filepath for Dockerfile

---

examples/examples_nodejs_test.go
examples/test-secrets-in-explicit-provider/csharp/Program.cs
examples/test-secrets-in-explicit-provider/ts/Dockerfile
examples/test-secrets-in-explicit-provider/ts/Pulumi.yaml
examples/test-secrets-in-explicit-provider/ts/index.ts
examples/test-secrets-in-explicit-provider/ts/package.json
examples/test-secrets-in-explicit-provider/ts/tsconfig.json

This test collects more evidence on https://github.com/pulumi/pulumi-dotnet/issues/142 
All the asserts pass in TypeScript, so this is good support for the hypothesis that the issue is peculiar to .NET SDK generation and does not affect other languages.

Add a Node test for secrets handling

---

provider/provider.go
provider/provider_test.go
provider/testdata/ignores-wildcard/basedir-modified-ignored-file/.dockerignore
provider/testdata/ignores-wildcard/basedir-modified-ignored-file/Dockerfile
provider/testdata/ignores-wildcard/basedir-modified-ignored-file/projects/foo/src/app.js
provider/testdata/ignores-wildcard/basedir-modified-included-file/.dockerignore
provider/testdata/ignores-wildcard/basedir-modified-included-file/Dockerfile
provider/testdata/ignores-wildcard/basedir-modified-included-file/projects/foo/src/app.js
provider/testdata/ignores-wildcard/basedir/.dockerignore
provider/testdata/ignores-wildcard/basedir/Dockerfile
provider/testdata/ignores-wildcard/basedir/projects/foo/src/app.js

This removes the `patternmatcher` library and replaces our context walk with the same library as used in Buildkit.
It turns out we *may* have already fixed #607 in #596, as the tests pass without changes to `provider.go`. However, there is logic in `fsutil.Walk()` absent in our previous implementation and it makes sense to limit the scope of the provider to reusing the routine from the `fsutil` library.
Fixes #607

Use fsutil.Walk() to compute context digest

---

provider/image.go
provider/provider.go

In #697, we added logic to Configure to determine and set the docker host address.
Because SSH uses a connection helper, in this PR we check for the connection helper string, and do not re-set DOCKER_HOST.
I verified this fixes the user-provided bug repro submitted with #706.
Fixes #706

Fix: docker host connection for SSH

---

.github/workflows/run-acceptance-tests.yml
examples/digitalocean-container-registry/csharp/Program.cs
examples/digitalocean-container-registry/go/main.go
examples/examples_dotnet_test.go
examples/examples_go_test.go
examples/examples_nodejs_test.go
examples/examples_py_test.go
examples/test-ssh-conn/README.md
examples/test-ssh-conn/ts/Pulumi.yaml
examples/test-ssh-conn/ts/index.ts
examples/test-ssh-conn/ts/package.json
examples/test-ssh-conn/ts/tsconfig.json
provider/image.go
provider/image_test.go

Pulumirpc's req.GetVariables flattens the configs into strings, even though `sshOpts` is properly a slice of strings. Worse, we get all sorts of extra escape characters. 
This pull request unmarshals `sshOpts` when needed and passes the resulting ssh flag options to the SSH connection helper.
Additionally, we set up a TS test for a remote Docker host using a Digitalocean Docker Droplet.
To make this work, there are some changes to the acceptance tests Workflow as well. This PR will need a followup in ci-mgmt to incorporate these changes properly.
This PR needs follow-up changes to ci-mgmt to 
Fixes #702.
- Read in SSH flags to the connection helper to avoid error in Configure
- Add integration test for SSH connections

Explicitly read in SSH config flags to the docker client configuration

---

examples/examples_nodejs_test.go
examples/test-local-repo-digest-ts/Dockerfile
examples/test-local-repo-digest-ts/Pulumi.yaml
examples/test-local-repo-digest-ts/index.ts
examples/test-local-repo-digest-ts/package.json
examples/test-local-repo-digest-ts/tsconfig.json
provider/cmd/pulumi-resource-docker/schema.json
provider/image.go
provider/resources.go
sdk/dotnet/Image.cs
sdk/go/docker/image.go
sdk/java/src/main/java/com/pulumi/docker/Image.java
sdk/java/src/main/java/com/pulumi/docker/ImageArgs.java
sdk/nodejs/image.ts
sdk/python/pulumi_docker/image.py

This pull request adds logic to inspect a recently built, local docker image, and uses its ID field to populate the `repoDigest` output for local images.
This value is the same as the "IMAGE ID" output from `docker images`, and it can be used, by itself, to run a container.
This extra logic allows us to additionally make repoDigest Required, making it far more straightforward to use.
Because the shape of this Output is slightly different depending on whether we're populating a pushed image vs a purely local one, the difference is documented.
Overall, this should address usability concerns for this field on pushed images as well.
Fixes #728
- Obtain image ID for local image from docker inspect object, and use it to set repoDigest for local images
- Make repoDigest Required and update …

Make repoDigest return for local image builds

---

provider/image.go

Switch docker daemon connection test to use cli.Ping instead of cli.PluginList. Resolves #737

Switch docker daemon connection test to use cli.Ping instead of cli.PluginList. Resolves #737

---

provider/hybrid.go

I figure that's the most likely use case, debugging our own code rather than upstream.
Tested locally.

Attach to native provider for debugging

---

examples/examples_yaml_test.go
provider/image.go
provider/provider.go

Fix #772 by enabling `KeepSecrets` in checkpoint encoding.
Adjusted an existing test to validate state file, test failure before the fix can be seen here: https://github.com/pulumi/pulumi-docker/actions/runs/6406254044/job/17390696422#step:27:685

Mark __inputs as secret

---

provider/provider.go
provider/provider_test.go

Fix https://github.com/pulumi/pulumi-docker/issues/780
When `registry` input relies on unknown outputs, the `diffUpdates` function currently panics. I added a test for this use case and reshuffled `diffUpdates` implementation to handle it properly and hopefully a bit more clearly.

Adjust diffUpdates to allow unknown values in preview

---

examples/aws-container-registry/ts/index.ts
examples/aws-container-registry/ts/package.json
examples/azure-container-registry/ts/step2/index.ts
examples/examples_nodejs_test.go
provider/cmd/pulumi-resource-docker/schema.json
provider/resources.go
sdk/dotnet/Inputs/DockerBuildArgs.cs
sdk/go/docker/image.go
sdk/go/docker/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/docker/inputs/DockerBuildArgs.java
sdk/nodejs/image.ts
sdk/nodejs/types/input.ts
sdk/nodejs/types/output.ts
sdk/python/pulumi_docker/_inputs.py

A somewhat bizarre fix for #676 
Let me try to explain what is going on in #676. The relevant snippet is (same as in the new test):
```
const image = new docker.Image("my-image", {
build: {
context: "app",
cacheFrom: {
images: [imageName]
},
}
```
Where `imageName` depends on another resource R. In the problematic scenario, the resource R is being replaced, which turns `imageName` into unknown. Unfortunately, this turns the entire `build` object into a big unknown instead of the desired effect of it keeping its shape with only an unknown value inside `cacheFrom`.
Here is a gRPC log:
```
{"build":"04da6b54-80e4-46f7-96ec-b56ff0331ba9","imageName":"04da6b54-80e4-46f7-96ec-b56ff0331ba9","registry":{"password":"04da6b54-80e4-46f7-96ec-b56ff0331ba9","server":"04da6b54-80e4-46f7-96ec-b56ff0331ba …
```

Prevent unknown inflection in build

---

examples/examples_yaml_test.go
examples/test-swarm/service-global/Pulumi.yaml
examples/test-swarm/service-replicated/Pulumi.yaml
examples/test-swarm/service/Pulumi.yaml
patches/0005-remove-service-default.patch
provider/cmd/pulumi-resource-docker/schema.json
sdk/dotnet/Inputs/ServiceModeArgs.cs
sdk/dotnet/Inputs/ServiceModeGetArgs.cs
sdk/dotnet/Outputs/ServiceMode.cs
sdk/go/docker/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/docker/inputs/ServiceModeArgs.java
sdk/java/src/main/java/com/pulumi/docker/outputs/ServiceMode.java
sdk/nodejs/types/input.ts
sdk/nodejs/types/output.ts
sdk/python/pulumi_docker/_inputs.py
sdk/python/pulumi_docker/outputs.py

Removes upstream's Service.global default as a workaround for https://github.com/pulumi/pulumi-terraform-bridge/issues/1095.
The included E2E test reproduced the issue locally and now passes with the fix. We'll see if it passes on CI -- GitHub might need some massaging to get a swarm working.
Fixes #401.

Fix Service replicated/global conflict

---

examples/examples_nodejs_test.go

Prior to this change, EditPath pointed to a non-existing directory so this test wasn't testing what's expected.. recent versions of Pulumi make this error a hard error; also we probably want the test to actually test the intended state transition encoded in the edit dir, hence this change.

Fix incorrect EditDir path in TestAzureContainerRegistry

---

provider/image.go

Users are unlikely to encounter this situation but I ran into it during some testing.
I've confirmed the fix locally. A regression test will be included in the upcoming buildx examples, since building the same dockerfile with `Image` and `buildx.Image` also reproduced the issue.
Fixes https://github.com/pulumi/pulumi-docker/issues/914

Fix a panic due to missing repo digests

---

provider/image.go
provider/provider.go
provider/provider_test.go

We could hang forever if we have irregular file types present, like pipes which never close.
Here we fix the issue by only hashing regular files.
Fixes https://github.com/pulumi/pulumi-docker/issues/614

Fix context bug which could hang forever

---

examples/test-ssh-conn/ts/Dockerfile
examples/test-ssh-conn/ts/index.ts
provider/image.go

The v25 upgrade made us sensitive to the ordering of our client options.
In particular if a host was specified last it would take precedence over the SSH dialer. This behavior was accounted for in the [upstream patch](https://github.com/pulumi/pulumi-docker/blob/f866a5a4ae5e67edee4a92b8930a6ac7ee1d305a/patches/0006-upgrade-docker-sdk.patch#L288-L289) but not in our own host resolution logic.
The PR adds a failing e2e test and a corresponding fix to our client options.

Fix SSH incompatibility with v25

---

examples/examples_nodejs_test.go
examples/examples_py_test.go
provider/go.mod
provider/image.go

This ID was added for diagnostics and we haven't seen any warnings reported so it should be safe to remove. More importantly the presence of the random label causes perpetual diffs, which is undesirable.
Fixes https://github.com/pulumi/pulumi-docker/issues/1219
Fixes https://github.com/pulumi/pulumi-docker/issues/1224
Refs https://github.com/pulumi/pulumi-docker/issues/846

Remove random build ID
