- docker/docker.ts
Partial fix for https://github.com/pulumi/pulumi-cloud/issues/539
> Pass logging messages to the right sink when doing docker operations.

- docker/package.json
- docker/tests/image/package.json
- docker/yarn.lock
Toward closing https://github.com/pulumi/pulumi/issues/1668
> Use the latest TS version.

- docker/docker.ts
- docker/package.json
- docker/yarn.lock
- tslint.json
Fixes https://github.com/pulumi/pulumi/issues/1940
> Associate errors throw during Docker runs with the right resource.

- docker/docker.ts
Addresses: https://github.com/pulumi/pulumi-docker/issues/41
Open to any suggestions, feel free to make edits.
> Fix repeated docker image tags

- sdk/nodejs/remoteImage.ts
This picks up some NodeJS codegen improvements.
> Regenerate docs with tf2pulumi v0.5.0

- examples/aws/index.ts
- sdk/nodejs/docker.ts
> Support configuring environment on `docker build` invocations

- .travis.yml
- examples/examples_test.go
Also actually run tests for PRs.
> Test with latest Docker

- Makefile
- sdk/nodejs/docker.ts
- sdk/nodejs/tests/image.spec.ts
- sdk/nodejs/tests/index.ts
- sdk/nodejs/tests/package.json
- sdk/nodejs/tests/tsconfig.json
Fixes https://github.com/pulumi/pulumi-docker/issues/97
> Don't throw when a user provides a numeric port in their docker repo-url

- CHANGELOG.md
- sdk/nodejs/docker.ts
- sdk/nodejs/image.ts
Add skip push functionality.
Issue: #85
> Skip push on image build.

- sdk/python/pulumi_docker/docker.py
- sdk/python/pulumi_docker/image.py
This fixes some issues I think, for registry PR #155. Tried the examples/aws-py and it worked to push to an ECR registry
> small fixes for push to registry

- CHANGELOG.md
- Makefile
- provider/cmd/pulumi-resource-docker/schema.json
- provider/go.mod
- provider/go.sum
- sdk/dotnet/Container.cs
- sdk/go/docker/container.go
- sdk/nodejs/container.ts
> Upgrade to v2.7.1 of the Docker Terraform Provider

- sdk/go/docker/docker.go
> Check err response of runDockerBuild in go SDK

- CHANGELOG.md
- examples/aws-py/__main__.py
- sdk/python/pulumi_docker/image.py
Fix: https://github.com/pulumi/pulumi-docker/issues/190
> Handle registry properties correctly

- sdk/dotnet/Docker.cs
- sdk/go/docker/customTypes.go
- sdk/nodejs/docker.ts
- sdk/python/pulumi_docker/docker.py
Make clear this is a list of strings.
> Improve extraoptions documentation

- CHANGELOG.md
- sdk/python/pulumi_docker/docker.py
The CacheFrom class was missing a constructor, and the test for whether
to pull from the cache had a condition inverted.
Fix #274.
> python: fix handling of cache_from

- examples/examples_py_test.go
Disable TestDockerfilePy and TestAwsPy
They are flaky and blocking releases.
> Disable Flaky Tests

- provider/cmd/pulumi-resource-docker/schema.json
- provider/image.go
- provider/provider.go
- provider/resources.go
> Implement create

- provider/cmd/pulumi-resource-docker/schema.json
- provider/image.go
- provider/resources.go
- sdk/dotnet/Image.cs
- sdk/go/docker/image.go
- sdk/java/src/main/java/com/pulumi/docker/Image.java
- sdk/nodejs/image.ts
- sdk/python/pulumi_docker/image.py
> image: fix outputs defined as optional

- provider/image.go
- provider/image_test.go
> Use connctionhelper to connect to remote Docker host.

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- Makefile
- sdk/java/build.gradle
- sdk/java/src/main/java/com/pulumi/docker/Container.java
- sdk/java/src/main/java/com/pulumi/docker/Image.java
- sdk/java/src/main/java/com/pulumi/docker/Network.java
- sdk/java/src/main/java/com/pulumi/docker/Plugin.java
- sdk/java/src/main/java/com/pulumi/docker/Provider.java
- sdk/java/src/main/java/com/pulumi/docker/RegistryImage.java
- sdk/java/src/main/java/com/pulumi/docker/RemoteImage.java
- sdk/java/src/main/java/com/pulumi/docker/Secret.java
- sdk/java/src/main/java/com/pulumi/docker/Service.java
- sdk/java/src/main/java/com/pulumi/docker/ServiceConfig.java
- sdk/java/src/main/java/com/pulumi/docker/Tag.java
- sdk/java/src/main/java/com/pulumi/docker/Utilities.java
- sdk/java/src/main/java/com/pulumi/docker/Volume.java
Besides codegen improvements, this allows the build to work with Gradle 8.x.
> Upgrade old pulumi-java to v0.9.7

- CONTRIBUTING.md
This PR seeks to directly address the enhancements requested in issue #768. Please make changes as needed to increase the clarity or add more context.
> Tips for building

- provider/cmd/pulumi-resource-docker/schema.json
- provider/resources.go
- sdk/nodejs/README.md
- sdk/python/pulumi_docker/README.md
Fixes https://github.com/pulumi/pulumi-docker/issues/896.
> Add upstream org for upgrade detection

- examples/aws-container-registry/go/go.mod
- examples/aws-container-registry/go/go.sum
- examples/azure-container-registry/go/go.mod
- examples/azure-container-registry/go/go.sum
- examples/digitalocean-container-registry/go/go.mod
- examples/digitalocean-container-registry/go/go.sum
- examples/docker-container-registry/go/go.mod
- examples/docker-container-registry/go/go.sum
- examples/dockerfile-go/go.mod
- examples/dockerfile-go/go.sum
- examples/gcp-container-registry/go/go.mod
- examples/gcp-container-registry/go/go.sum
- examples/go.mod
- examples/go.sum
- examples/multi-stage-build-go/go.mod
- examples/multi-stage-build-go/go.sum
- examples/nginx-go/go.mod
- examples/nginx-go/go.sum
- sdk/go.mod
- sdk/go.sum
Combining multiple dependencies PRs into one.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* bump the go_modules group across 10 directories with 1 update (#940) @app/dependabot
* bump the go_modules group across 7 directories with 1 update (#939) @app/dependabot
* bump the go_modules group across 9 directories with 1 update (#938) @app/dependabot
* bump the go_modules group across 11 directories with 1 update (#937) @app/dependabot
> Combined dependencies PR

- provider/image.go
Fixes https://github.com/pulumi/pulumi-docker/issues/989
> Remove warning about gitignore

- docs/_index.md
This pull request updates the index doc for this provider, which was not being updated due to a missed target in the Makefile.
Fixes #1343.
> Regenerate index docs
